[package]
name = "pigeon-mock"
version = "0.1.0"
edition = "2021"

[lib]
name = "pigeon"

[dependencies]
graphql = { git = "https://github.com/getlipa/wild", tag = "v1.21.3" }
honeybadger-mock = { path = "../honeybadger" }
