[package]
name = "eel"
version = "0.1.0"
edition = "2021"

[features]
nigiri = []

[dependencies]
aes = "0.8.1"
aes-gcm = "0.10.1"
bdk = { version = "0.26.0", default-features = false, features = ["keys-bip39"] }
bitcoin = "0.29.2"
cbc = "0.1.2"
cipher = { version = "0.4.3", features = ["block-padding", "alloc"] }
ecies = "0.2.3"
esplora-client = { version = "0.3.0", default-features = false, features = ["blocking"] }
futures = "0.3.24"
lightning = { version = "0.0.113", features = ["max_level_trace"] }
lightning-background-processor = "0.0.113"
lightning-invoice = "0.21.0"
lightning-net-tokio = "0.0.113"
lightning-persister = "0.0.113"
lightning-rapid-gossip-sync = "0.0.113"
log = "0.4.17"
prost = "0.11.0"
rand = "0.8.5"
reqwest = { version = "0.11.12", default-features = false, features = ["blocking", "rustls-tls"] }
# Explicitly depend on secp256k1 for secp256k1::SECP256K1.
secp256k1 = { version = "0.24.3", features = ["global-context"] }
thiserror = "1.0.34"
tokio = { version = "1.21.1", features = ["rt-multi-thread", "time", "sync"] }
tonic = "0.8.2"

perro = { git = "https://github.com/getlipa/perro", tag = "v1.0.0" }

[dev-dependencies]
ctor = "0.1.26"
serde_json = "1.0"
serial_test = { version =  "1.0.0", features = ["file_locks"] }
simplelog = { version = "0.12.0", features = ["test"] }
storage-mock = { path = "../util/storage-mock" }

[build-dependencies]
tonic-build = "0.8.2"
