version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "perro"
      - dependency-name: "honey-badger"
      - dependency-name: "mole"
      - dependency-name: "chameleon"
      - dependency-name: "lightning-rapid-gossip-sync"
      - dependency-name: "lightning-background-processor"
      - dependency-name: "lightning-transaction-sync"
      - dependency-name: "lightning-net-tokio"
      - dependency-name: "lightning-persister"
      - dependency-name: "lightning-invoice"
