[package]
name = "lipalightninglib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]
name = "uniffi_lipalightninglib"

[features]
nigiri = []

[dependencies]
eel = { path = "eel" }
log = "0.4.17"
uniffi = "0.22.0"
storage-mock = { path = "util/storage-mock" }
thiserror = "1.0.38"

[target.'cfg(target_os = "ios")'.dependencies]
oslog = "0.2.0"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.12.0"

[package.metadata.cross.build]
pre-build = ["apt update --no-show-upgraded && apt install --yes protobuf-compiler"]

[build-dependencies]
camino = "1.1.1"
uniffi_bindgen = "0.23.0"
