[workspace]
members = [
    "eel",
]

[package]
name = "lipalightninglib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "uniffi_lipalightninglib"

[features]
nigiri = []

[dependencies]
eel = { path = "eel" }

log = "0.4.18"
thiserror = "1.0.40"
uniffi = "0.23.0"

chameleon = { git = "https://github.com/getlipa/wild", tag = "v1.1.1" }
honey-badger = { git = "https://github.com/getlipa/wild", tag = "v1.1.1" }
mole = { git = "https://github.com/getlipa/wild", tag = "v1.1.1" }
perro = { git = "https://github.com/getlipa/perro", tag = "v1.0.1" }

[dev-dependencies]
bitcoin = "0.29.2"
chrono = { version = "0.4.26", default-features = false }
colored = "2.0.0"
ctor = "0.2.2"
esplora-client = { version = "0.5.0", default-features = false, features = ["blocking"] }
rand = "0.8.5"
rustyline = { version = "11.0.0", features = ["derive"] }
serde_json = "1.0"
serial_test = { version =  "2.0.0", features = ["file_locks"] }
simplelog = { version = "0.12.0", features = ["test"] }
strip-ansi-escapes = "0.1.1"

[target.'cfg(target_os = "ios")'.dependencies]
oslog = "0.2.0"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13.0"

[package.metadata.cross.build]
pre-build = ["apt update --no-show-upgraded && apt install --yes protobuf-compiler"]

[build-dependencies]
camino = "1.1.1"
uniffi_bindgen = "0.23.0"
