[package]
name = "lipalightninglib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "uniffi_lipalightninglib"

[dependencies]
tokio = { version = "1", features = [ "io-util", "macros", "rt", "rt-multi-thread", "sync", "net", "time" ] }
uniffi = "0.19.6"
thiserror = "1.0"
lightning = { version = "0.0.110", features = ["max_level_trace"] }
lightning-invoice = { version = "0.18.0" }
lightning-net-tokio = { version = "0.0.110" }
lightning-background-processor = { version = "0.0.110" }
bitcoin = { version = "0.28.1", features = ["use-serde"] }
reqwest = { version = "0.11", features = ["json", "socks"] }
rand = "0.4"
log = "0.4.17"
serde = "1.0.144"
serde_json = { version = "1.0" }

# needed for ldk-sample
base64 = "0.13.0"
futures = "0.3"
time = "0.3.12"
bitcoin-bech32 = "0.12"
bech32 = "0.9"
libc = "0.2.126"

[dev-dependencies]
simplelog = "0.12.0"

[target.'cfg(target_os = "ios")'.dependencies]
oslog = "0.2.0"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.11"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winbase"] }

[build-dependencies]
uniffi_bindgen = "0.19.6"
camino = "1.1.1"