[package]
name = "lipalightninglib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "uniffi_lipalightninglib"

[dependencies]
bdk = { version = "0.22.0", features = ["keys-bip39"] }
bitcoin = "0.28.1"
lightning = { version = "0.0.110", features = ["max_level_trace"] }
log = "0.4.17"
rand = "0.8.5"
thiserror = "1.0.34"
uniffi = "0.20.0"

[dev-dependencies]
simplelog = "0.12.0"

[target.'cfg(target_os = "ios")'.dependencies]
oslog = "0.2.0"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.11"

[build-dependencies]
camino = "1.1.1"
uniffi_bindgen = "0.19.6"
