[package]
name = "lipalightninglib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "uniffi_lipalightninglib"

[dependencies]
uniffi = "0.19.6"
lightning = { version = "0.0.110", features = ["max_level_trace"] }
log = "0.4.17"

[dev-dependencies]
simplelog = "0.12.0"

[target.'cfg(target_os = "ios")'.dependencies]
oslog = "0.2.0"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.11"

[build-dependencies]
uniffi_bindgen = "0.19.6"
camino = "1.1.1"