[package]
name = "lipalightninglib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "uniffi_lipalightninglib"

[dependencies]
bdk = { version = "0.22.0", features = ["keys-bip39"] }
bitcoin = "0.28.1"
lightning = { version = "0.0.110", features = ["max_level_trace"] }
log = "0.4.17"
rand = "0.8.5"
thiserror = "1.0.34"
tokio = { version = "1.21.1", features = ["rt-multi-thread", "time"] }
uniffi = "0.20.0"

# Explicitly specify a library for tls, otherwise defaults to openssl,
# which fails on Android targets.
# Might be fixed in https://github.com/bitcoindevkit/rust-esplora-client/issues/11
reqwest = { version = "0.11", default-features = false, features = ["json", "socks", "rustls-tls"] }
esplora-client = { git = "https://github.com/bitcoindevkit/rust-esplora-client", default-features = false, features = ["async"] }

[dev-dependencies]
bitcoin_hashes = "0.11.0"
simplelog = { version ="0.12.0", features = ["test"] }

[target.'cfg(target_os = "ios")'.dependencies]
oslog = "0.2.0"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.11"

[build-dependencies]
camino = "1.1.1"
uniffi_bindgen = "0.20.0"
