[workspace]
members = [
    "eel",
]

[package]
name = "lipalightninglib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "uniffi_lipalightninglib"

[features]
nigiri = []

[dependencies]
eel = { path = "eel" }

log = "0.4.19"
simplelog = { version = "0.12.0" }
thiserror = "1.0.43"
uniffi = "0.24.1"

chameleon = { git = "https://github.com/getlipa/wild", tag = "v1.2.1" }
honey-badger = { git = "https://github.com/getlipa/wild", tag = "v1.2.1" }
mole = { git = "https://github.com/getlipa/wild", tag = "v1.2.1" }
perro = { git = "https://github.com/getlipa/perro", tag = "v1.0.1" }

[dev-dependencies]
bitcoin = "0.29.2"
chrono = { version = "0.4.26", default-features = false }
colored = "2.0.4"
ctor = "0.2.3"
esplora-client = { version = "0.5.0", default-features = false, features = ["blocking"] }
rand = "0.8.5"
rustyline = { version = "12.0.0", features = ["derive"] }
serde_json = "1.0"
serial_test = { version =  "2.0.0", features = ["file_locks"] }
strip-ansi-escapes = "0.1.1"

[package.metadata.cross.build]
pre-build = ["apt update --no-show-upgraded && apt install --yes protobuf-compiler"]

[build-dependencies]
camino = "1.1.6"
uniffi_bindgen = "0.24.0"

# Enable debug symbols for our and LDK crates, but not others.
[profile.release]
debug = 1
[profile.release.package."*"]
debug = 0
[profile.release.package.eel]
debug = 1
[profile.release.package.chameleon]
debug = 1
[profile.release.package.honey-badger]
debug = 1
[profile.release.package.mole]
debug = 1
[profile.release.package.lightning]
debug = 1
[profile.release.package.lightning-background-processor]
debug = 1
[profile.release.package.lightning-invoice]
debug = 1
[profile.release.package.lightning-net-tokio]
debug = 1
[profile.release.package.lightning-persister]
debug = 1
[profile.release.package.lightning-rapid-gossip-sync]
debug = 1
[profile.release.package.lightning-transaction-sync]
debug = 1
