[package]
name = "lipalightninglib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "uniffi_lipalightninglib"

[features]
nigiri = []

[dependencies]
aes = "0.8.1"
bdk = { version = "0.24.0", default-features = false, features = ["keys-bip39"] }
bitcoin = "0.29.2"
cbc = "0.1.2"
cipher = { version = "0.4.3", features = ["block-padding", "alloc"] }
futures = "0.3.24"
lightning = { version = "0.0.112", features = ["max_level_trace"] }
lightning-background-processor = "0.0.112"
lightning-net-tokio = "0.0.112"
lightning-rapid-gossip-sync = "0.0.112"
lightning-invoice = "0.20.0"
log = "0.4.17"
prost = "0.11.0"
rand = "0.8.5"
secp256k1 = { version = "0.24.1", features = [ "rand" ] }
thiserror = "1.0.34"
tokio = { version = "1.21.1", features = ["rt-multi-thread", "time", "sync"] }
tonic = "0.8.2"
uniffi = "0.21.0"
reqwest = { version = "0.11.12", default-features = false, features = ["blocking", "rustls-tls"] }

esplora-client = { version = "0.2.0" , default-features = false, features = ["blocking"] }

[dev-dependencies]
serde_json = "1.0"
simplelog = { version ="0.12.0", features = ["test"] }
storage-mock = { path = "util/storage-mock" }

[target.'cfg(target_os = "ios")'.dependencies]
oslog = "0.2.0"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.11"

[package.metadata.cross.build]
pre-build = ["apt update --no-show-upgraded && apt install --yes protobuf-compiler"]

[build-dependencies]
camino = "1.1.1"
tonic-build = "0.8.2"
uniffi_bindgen = "0.21.0"
