# Temporary fix - Once we move to a newer cross version, this file can be removed.
# Checkout https://github.com/cross-rs/cross/issues/1217#issuecomment-1465167806 for details. 
[target.aarch64-linux-android]
image = "ghcr.io/cross-rs/aarch64-linux-android:main"
[target.i686-linux-android]
image = "ghcr.io/cross-rs/i686-linux-android:main"
[target.x86_64-linux-android]
image = "ghcr.io/cross-rs/x86_64-linux-android:main"

[build]
pre-build = [
    "apt install --yes unzip",
    "curl --location --remote-name https://github.com/protocolbuffers/protobuf/releases/download/v3.15.8/protoc-3.15.8-linux-x86_64.zip",
    "unzip protoc-3.15.8-linux-x86_64.zip -d /opt/protoc",
    "chmod --recursive 755 /opt/protoc"
]

[build.env]
passthrough = ["PROTOC=/opt/protoc/bin/protoc"]
