// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    int32_t capacity;
    int32_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef int32_t (*ForeignCallback)(uint64_t, int32_t, RustBuffer, RustBuffer *_Nonnull);

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H

void ffi_lipalightninglib_f0e0_LipaLightning_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull lipalightninglib_f0e0_LipaLightning_new(
      RustBuffer config,uint64_t persist_callback,
    RustCallStatus *_Nonnull out_status
    );
void lipalightninglib_f0e0_LipaLightning_stop(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer lipalightninglib_f0e0_LipaLightning_get_my_node_id(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer lipalightninglib_f0e0_LipaLightning_get_node_info(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void lipalightninglib_f0e0_LipaLightning_connect_open_channel(
      void*_Nonnull ptr,RustBuffer node_id,RustBuffer node_address,uint64_t channel_value_sat,
    RustCallStatus *_Nonnull out_status
    );
void lipalightninglib_f0e0_LipaLightning_send_payment(
      void*_Nonnull ptr,RustBuffer invoice_str,
    RustCallStatus *_Nonnull out_status
    );
void lipalightninglib_f0e0_LipaLightning_send_spontaneous_payment(
      void*_Nonnull ptr,uint64_t amout_msat,RustBuffer node_id,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer lipalightninglib_f0e0_LipaLightning_create_invoice(
      void*_Nonnull ptr,uint64_t amount_msat,uint32_t expiry_secs,
    RustCallStatus *_Nonnull out_status
    );
void ffi_lipalightninglib_f0e0_PersistCallback_init_callback(
      ForeignCallback  _Nonnull callback_stub,
    RustCallStatus *_Nonnull out_status
    );
void lipalightninglib_f0e0_init_logger_once(
      
    RustCallStatus *_Nonnull out_status
    );
RustBuffer ffi_lipalightninglib_f0e0_rustbuffer_alloc(
      int32_t size,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer ffi_lipalightninglib_f0e0_rustbuffer_from_bytes(
      ForeignBytes bytes,
    RustCallStatus *_Nonnull out_status
    );
void ffi_lipalightninglib_f0e0_rustbuffer_free(
      RustBuffer buf,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer ffi_lipalightninglib_f0e0_rustbuffer_reserve(
      RustBuffer buf,int32_t additional,
    RustCallStatus *_Nonnull out_status
    );
