services:
  lspd-lnd:
    container_name: lspd-lnd
    build: ./lnd-zero-conf
    ports:
      - '9739:9739'
      - '10013:10013'
    healthcheck:
      test: ["CMD-SHELL", "lncli getinfo | grep -q '\"synced_to_chain\": true'"]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 3s

  db:
    container_name: lspd-db
    image: 'postgres:14.5-alpine'
    environment:
      POSTGRES_USER: lipauser
      POSTGRES_PASSWORD: lipapassword
      POSTGRES_DB: lipadb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=lipauser --dbname=lipadb"]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 3s
    volumes:
      - ./db-init.sh:/docker-entrypoint-initdb.d/db-init.sh
      - ../submodules/lspd/postgresql/migrations/:/migrations/

  lspd:
    build:
      context: ../submodules/lspd
      dockerfile: ../../lspd/Dockerfile
    ports:
      - '6666:6666'
    depends_on:
      db:
        condition: service_healthy
      lspd-lnd:
        condition: service_healthy
    env_file:
      - lnd.env
    environment:
      DATABASE_URL: postgresql://lipauser:lipapassword@lspd-db:5432/lipadb
      LISTEN_ADDRESS: 0.0.0.0:6666
      LND_ADDRESS: lspd-lnd:10013
      # Generated by `hal key generate`
      LSPD_PRIVATE_KEY: 6ca37dfd24b41046ff3bb904cd36710176352b71dbeaf8fbfaa162043e3cbd6b
      NODE_HOST: 127.0.0.1:9739
      TOKEN: iQUvOsdk4ognKshZB/CKN2vScksLhW8i13vTO+8SPvcyWJ+fHi8OLgUEvW1N3k2l

networks:
  default:
    name: nigiri
    external: true
