services:
  bitcoin:
    container_name: rgs-bitcoin
    image: ruimarinho/bitcoin-core:alpine
    command:
      - -regtest=1
      - -server=1
      - -printtoconsole
      - -rpcallowip=0.0.0.0/0
      - -rpcbind=0.0.0.0
      - -rpcuser=admin1
      - -rpcpassword=123
      - -rpcport=18445
      - -port=18446
      - -rest
      - -addnode=bitcoin:18444
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "bitcoin-cli -rpcport=18445 -rpcuser=admin1 -rpcpassword=123 getpeerinfo" ]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 3s

  cln:
    container_name: rgs-cln
    image: elementsproject/lightningd:latest
    environment:
      EXPOSE_TCP: "true"
    command:
      - --network=regtest
      - --bind-addr=0.0.0.0:9937
      - --bitcoin-rpcconnect=rgs-bitcoin:18445
      - --bitcoin-rpcuser=admin1
      - --bitcoin-rpcpassword=123
      - --log-level=debug
      - --alias=rgs-cln
    ports:
      - 9937:9937
    volumes:
      - ./cln/hsm_secret:/root/.lightning/regtest/hsm_secret
    restart: unless-stopped
    depends_on:
      bitcoin:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "lightning-cli --network=regtest getinfo" ]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 3s

  db:
    container_name: rgs-db
    image: 'postgres:14.5-alpine'
    environment:
      POSTGRES_USER: lipauser
      POSTGRES_PASSWORD: lipapassword
      POSTGRES_DB: lipadb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=lipauser --dbname=lipadb"]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 3s

  rgs:
    build: ./rgs-server
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
      bitcoin:
        condition: service_healthy
      cln:
        condition: service_healthy
    environment:
      RAPID_GOSSIP_SYNC_SERVER_DB_HOST: rgs-db
      RAPID_GOSSIP_SYNC_SERVER_DB_USER: lipauser
      RAPID_GOSSIP_SYNC_SERVER_DB_PASSWORD: lipapassword
      RAPID_GOSSIP_SYNC_SERVER_DB_NAME: lipadb
      BITCOIN_REST_DOMAIN: rgs-bitcoin
      BITCOIN_REST_PORT: 18445
      BITCOIN_REST_PATH: /rest/
      SNAPSHOT_CALCULATION_INTERVAL_SECS: 20

networks:
  default:
    name: nigiri
    external: true
