on: [push, pull_request]
name: Static code analysis
jobs:
  security-audit:
    name: Security audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
      - name: Install security audit
        run: cargo install cargo-audit
      - name: Run security audit
        run: cargo audit
  fmt_check:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          components: rustfmt
      - name: Check code formatting
        run: cargo fmt -- --check
  clippy_check:
    name: Clippy check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          components: clippy
      - name: Clippy
        run: cargo clippy
  unused_dependencies:
    name: Look for unused dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          override: true
      - name: Install unused dependency checker
        run: cargo install cargo-udeps --locked
      - name: Run unused dependency checker
        run: cargo +nightly udeps --all-targets
