name: Integration Tests with Nigiri

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Nigiri
        uses: vulpemventures/nigiri-github-action@master
        with:
          use_liquid: false
          use_ln: true
      - name: Setup LND
        run: |
          sleep 10 # wait for Nigiri to start
          nigiri faucet lnd
          echo "LSP_NODE_PUB_KEY=$(nigiri lnd getinfo | jq -r .identity_pubkey)" >> $GITHUB_ENV
          echo "LSP_NODE_ADDRESS=$(hostname -I | awk '{print $1}'):9735" >> $GITHUB_ENV
      - name: Run integration tests
        run: |
          cargo test --test '*' # runs integration tests only