name: Integration Tests with Nigiri

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:

      - name: Install Nigiri
        run: |
          mkdir ~/.nigiri; cd ~/.nigiri
          curl https://travis.nigiri.network | bash; cd
          docker-compose -f ~/.nigiri/docker-compose.yml up -d

