name: Integration Tests with Nigiri

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.2.0
      - name: Run Nigiri
        uses: vulpemventures/nigiri-github-action@master
        with:
          use_liquid: false
          use_ln: true
      - name: Set environment variables
        run: echo "BACKEND_BASE_URL=${{ secrets.BACKEND_BASE_URL }}" >> $GITHUB_ENV
      - name: Run integration tests
        run: make integrationtests
