name: Integration Tests with Nigiri

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Nigiri
        uses: vulpemventures/nigiri-github-action@master
        with:
          use_liquid: false
          use_ln: true
      - name: Prepare integration tests
        run: |
          echo "RUNNING_ON_CI=true" >> $GITHUB_ENV
      - name: Run integration tests
        run: |
          cargo test --features nigiri --test '*' -- --test-threads 1 # runs integration tests only and sequentially
